spring:
  application:
    name: fullmooney-tistory-com
  profiles:
    active: local
  devtools:
    livereload:
      port: 18090
      enabled: true
  redis:
    url: localhost
    port: 6379
    password: fullmooney
    database: 0
    
# redis
lettuce:
  connect-timeout: 500
  command-timeout: 500

logging:
  config: classpath:logback-spring.xml
  
#log path
logs:
  absolute:
    path: C:/dev/log
  level:
    root: INFO
    com: DEBUG
  name: fullmooney-tistory-com

logbook:
  exclude:
  - '**/health'
  - '**/v3/api-docs/**'
  - '**/v2/api-docs/**'
  - '**/v1/api-docs/**'
  - '**/swagger-resources/**'
  - '**/configuration/security'
  - '**/swagger'
  - '**/csrf'
  - '**/error'
  - '**/configuration'
  - '**/swagger-ui.html'
  - '**/favicon.*'
  - '**/h2-console/**'
  - '**/webjars/**'
  - '**/swagger-ui/**'
  - '**/swagger-ui/*'
  - '**/swagger-resources/**'
  - '**/etrack/exportArchive'
  - '**/*-stream'
  - '**/admin/**'